server:
  port: 3000
spring:
  datasource:
    username: root
    password: woshifeng159
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.133.147.167:3306/j-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
logging:
  config: classpath:log4j2-spring.xml